"""initial schema

Revision ID: 1e58d7778bf7
Revises: 
Create Date: 2026-06-19 00:13:01.629557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e58d7778bf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent_type IN ('coordinator', 'executor', 'hybrid')", name='ck_agents_agent_type'),
    sa.CheckConstraint("status IN ('active', 'inactive', 'retired')", name='ck_agents_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='company'
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=150), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False, schema='company')
    op.create_table('pipeline_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='company'
    )
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_type', sa.String(length=100), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='company'
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='company'
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('security_reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IN ('internal', 'third_party', 'foundation')", name='ck_skills_origin'),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')", name='ck_skills_risk_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_skills_name_version'),
    schema='company'
    )
    op.create_table('agent_capacities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=False),
    sa.Column('max_daily_tasks', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_concurrent_tasks >= 1', name='ck_agent_capacities_max_concurrent_tasks_positive'),
    sa.ForeignKeyConstraint(['agent_id'], ['company.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', name='uq_agent_capacities_agent_id'),
    schema='company'
    )
    op.create_table('agent_cost_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('rate_unit', sa.String(length=20), nullable=False),
    sa.Column('rate_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rate_unit IN ('per_task', 'per_hour', 'per_token', 'per_execution')", name='ck_agent_cost_rates_rate_unit'),
    sa.CheckConstraint('rate_amount >= 0', name='ck_agent_cost_rates_amount_nonneg'),
    sa.ForeignKeyConstraint(['agent_id'], ['company.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('agent_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('inheritable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['company.agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['company.skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'skill_id', name='uq_agent_skills_agent_skill'),
    schema='company'
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('approval_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.String(length=150), nullable=False),
    sa.Column('decided_by', sa.String(length=150), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['company.policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_index('ix_approvals_entity', 'approvals', ['entity_type', 'entity_id'], unique=False, schema='company')
    op.create_table('pipeline_template_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage_type', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['company.pipeline_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'order_index', name='uq_template_stage_order'),
    schema='company'
    )
    op.create_table('product_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['company.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_product_modules_product_id_name'),
    schema='company'
    )
    op.create_table('product_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'in_development', 'in_test', 'published', 'deprecated')", name='ck_product_versions_status'),
    sa.ForeignKeyConstraint(['product_id'], ['company.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', name='uq_product_versions_product_id_version'),
    schema='company'
    )
    op.create_table('sub_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('permission_scope', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'retired')", name='ck_sub_agents_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['company.agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'name', name='uq_sub_agents_agent_id_name'),
    schema='company'
    )
    op.create_table('pipeline_template_required_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_stage_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_stage_id'], ['company.pipeline_template_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_version_id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='planned', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_version_id'], ['company.product_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_version_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'ready', 'released', 'cancelled')", name='ck_releases_status'),
    sa.ForeignKeyConstraint(['product_version_id'], ['company.product_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('sub_agent_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_agent_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['company.skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_agent_id'], ['company.sub_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_agent_id', 'skill_id', name='uq_sub_agent_skills_sub_agent_skill'),
    schema='company'
    )
    op.create_table('planning_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='new', nullable=False),
    sa.Column('priority', sa.String(length=16), server_default='medium', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('target_version_id', sa.UUID(), nullable=True),
    sa.Column('baselined', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("item_type IN ('feature', 'bug', 'hotfix', 'improvement', 'technical_debt', 'refactoring', 'security_fix', 'research', 'documentation')", name='ck_planning_items_item_type'),
    sa.CheckConstraint("status IN ('new', 'triaged', 'scoped', 'baselined', 'in_progress', 'done', 'rejected', 'cancelled')", name='ck_planning_items_status'),
    sa.ForeignKeyConstraint(['project_id'], ['company.projects.id'], ),
    sa.ForeignKeyConstraint(['target_version_id'], ['company.product_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('project_pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['company.projects.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['company.pipeline_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('project_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('estimated_start_date', sa.Date(), nullable=True),
    sa.Column('estimated_end_date', sa.Date(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['company.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('bug_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), server_default='medium', nullable=False),
    sa.Column('environment', sa.String(length=255), nullable=True),
    sa.Column('reproduction_steps', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('detected_version_id', sa.UUID(), nullable=True),
    sa.Column('fixed_in_version_id', sa.UUID(), nullable=True),
    sa.Column('planning_item_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_bug_reports_severity'),
    sa.ForeignKeyConstraint(['detected_version_id'], ['company.product_versions.id'], ),
    sa.ForeignKeyConstraint(['fixed_in_version_id'], ['company.product_versions.id'], ),
    sa.ForeignKeyConstraint(['planning_item_id'], ['company.planning_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planning_item_id'),
    schema='company'
    )
    op.create_table('feature_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('business_value', sa.Text(), nullable=True),
    sa.Column('planning_item_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planning_item_id'], ['company.planning_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planning_item_id'),
    schema='company'
    )
    op.create_table('pipeline_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage_type', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['company.project_pipelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'order_index', name='uq_pipeline_stage_order'),
    schema='company'
    )
    op.create_table('plan_baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope_snapshot', sa.Text(), nullable=True),
    sa.Column('cost_snapshot', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('end_date_snapshot', sa.Date(), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_plan_id'], ['company.project_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('project_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planning_item_id', sa.UUID(), nullable=True),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['company.project_tasks.id'], ),
    sa.ForeignKeyConstraint(['planning_item_id'], ['company.planning_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('triage_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planning_item_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('accepted', 'rejected', 'deferred', 'merged', 'duplicate')", name='ck_triage_decisions_outcome'),
    sa.ForeignKeyConstraint(['planning_item_id'], ['company.planning_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('version_scope_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('planning_item_id', sa.UUID(), nullable=False),
    sa.Column('product_version_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planning_item_id'], ['company.planning_items.id'], ),
    sa.ForeignKeyConstraint(['product_version_id'], ['company.product_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planning_item_id', 'product_version_id', name='uq_version_scope_items_planning_item_version'),
    schema='company'
    )
    op.create_table('change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('plan_baseline_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('affects_scope', sa.Boolean(), nullable=False),
    sa.Column('affects_schedule', sa.Boolean(), nullable=False),
    sa.Column('affects_cost', sa.Boolean(), nullable=False),
    sa.Column('adds_features', sa.Boolean(), nullable=False),
    sa.Column('removes_features', sa.Boolean(), nullable=False),
    sa.Column('introduces_critical_bug_fix', sa.Boolean(), nullable=False),
    sa.Column('changes_agents', sa.Boolean(), nullable=False),
    sa.Column('changes_skills', sa.Boolean(), nullable=False),
    sa.Column('changes_architecture', sa.Boolean(), nullable=False),
    sa.Column('changes_security', sa.Boolean(), nullable=False),
    sa.Column('schedule_delta_days', sa.Integer(), nullable=True),
    sa.Column('cost_delta', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_baseline_id'], ['company.plan_baselines.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['company.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('pipeline_stage_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_stage_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_stage_id'], ['company.pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['company.pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', 'depends_on_stage_id', name='uq_stage_dependency_pair'),
    schema='company'
    )
    op.create_table('pipeline_stage_gates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('gate_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['company.pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('sub_agent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['company.agents.id'], ),
    sa.ForeignKeyConstraint(['sub_agent_id'], ['company.sub_agents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['company.project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['company.project_tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['company.project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('task_required_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('minimum_proficiency', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['company.skills.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['company.project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('task_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('executor_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_summary', sa.Text(), nullable=True),
    sa.Column('evidence_ref', sa.String(length=500), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['company.task_assignments.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['company.project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.Enum('PRD', 'SPEC', 'DATA_SPEC', 'BUSINESS_RULE_SPEC', 'SECURITY_SPEC', 'SOURCE_CODE', 'MIGRATION', 'TEST_REPORT', 'RELEASE_NOTES', 'PULL_REQUEST', 'DEPLOYMENT_PACKAGE', 'APPROVAL_RECORD', 'OTHER', name='artifact_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='artifact_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pipeline_stage_id', sa.UUID(), nullable=True),
    sa.Column('task_execution_id', sa.UUID(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_stage_id'], ['company.pipeline_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_execution_id'], ['company.task_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('artifact_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', 'SUPERSEDED', name='artifact_version_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('location_uri', sa.String(length=2048), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('produced_by_task_execution_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['company.artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produced_by_task_execution_id'], ['company.task_executions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'version_number', name='uq_artifact_version_number'),
    schema='company'
    )
    op.create_table('pipeline_stage_required_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('is_fulfilled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['company.artifacts.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['company.pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_stage_required_artifacts', schema='company')
    op.drop_table('artifact_versions', schema='company')
    op.drop_table('artifacts', schema='company')
    op.drop_table('task_executions', schema='company')
    op.drop_table('task_required_skills', schema='company')
    op.drop_table('task_dependencies', schema='company')
    op.drop_table('task_assignments', schema='company')
    op.drop_table('pipeline_stage_gates', schema='company')
    op.drop_table('pipeline_stage_dependencies', schema='company')
    op.drop_table('change_requests', schema='company')
    op.drop_table('version_scope_items', schema='company')
    op.drop_table('triage_decisions', schema='company')
    op.drop_table('project_tasks', schema='company')
    op.drop_table('plan_baselines', schema='company')
    op.drop_table('pipeline_stages', schema='company')
    op.drop_table('feature_requests', schema='company')
    op.drop_table('bug_reports', schema='company')
    op.drop_table('project_plans', schema='company')
    op.drop_table('project_pipelines', schema='company')
    op.drop_table('planning_items', schema='company')
    op.drop_table('sub_agent_skills', schema='company')
    op.drop_table('releases', schema='company')
    op.drop_table('projects', schema='company')
    op.drop_table('pipeline_template_required_artifacts', schema='company')
    op.drop_table('sub_agents', schema='company')
    op.drop_table('product_versions', schema='company')
    op.drop_table('product_modules', schema='company')
    op.drop_table('pipeline_template_stages', schema='company')
    op.drop_index('ix_approvals_entity', table_name='approvals', schema='company')
    op.drop_table('approvals', schema='company')
    op.drop_table('agent_skills', schema='company')
    op.drop_table('agent_cost_rates', schema='company')
    op.drop_table('agent_capacities', schema='company')
    op.drop_table('skills', schema='company')
    op.drop_table('products', schema='company')
    op.drop_table('policies', schema='company')
    op.drop_table('pipeline_templates', schema='company')
    op.drop_index('ix_audit_events_entity', table_name='audit_events', schema='company')
    op.drop_table('audit_events', schema='company')
    op.drop_table('agents', schema='company')
    # ### end Alembic commands ###
