"""add policy_id to project_tasks

Revision ID: 2084ac3d9413
Revises: 827968624658
Create Date: 2026-06-30 00:49:13.724684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2084ac3d9413'
down_revision: Union[str, Sequence[str], None] = '827968624658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tasks', sa.Column('policy_id', sa.UUID(), nullable=True), schema='company')
    op.create_foreign_key(None, 'project_tasks', 'policies', ['policy_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_tasks', schema='company', type_='foreignkey')
    op.drop_column('project_tasks', 'policy_id', schema='company')
    # ### end Alembic commands ###
