"""add_project_forgerouter_configs

Revision ID: 533f6aca2337
Revises: 1a3c3751cd51
Create Date: 2026-06-27 12:40:12.911043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533f6aca2337'
down_revision: Union[str, Sequence[str], None] = '1a3c3751cd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_forgerouter_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('claude_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('codex_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('antigravity_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('configured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['company.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id'),
    schema='company'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_forgerouter_configs', schema='company')
    # ### end Alembic commands ###
