"""add tool_version_status and tool_sync_setting tables

Revision ID: 576dae402892
Revises: 91232bae107f
Create Date: 2026-06-22 00:54:00.147111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576dae402892'
down_revision: Union[str, Sequence[str], None] = '91232bae107f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_sync_setting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.create_table('tool_version_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool', sa.String(length=30), nullable=False),
    sa.Column('installed_version', sa.String(length=100), nullable=True),
    sa.Column('latest_version', sa.String(length=255), nullable=True),
    sa.Column('update_available', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tool IN ('hermes', 'claude', 'codex', 'antigravity')", name='ck_tool_version_status_tool'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool'),
    schema='company'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_version_status', schema='company')
    op.drop_table('tool_sync_setting', schema='company')
    # ### end Alembic commands ###
