"""add entity_type entity_id to policies

Revision ID: 827968624658
Revises: e19cfcf39941
Create Date: 2026-06-30 00:37:45.615190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827968624658'
down_revision: Union[str, Sequence[str], None] = 'e19cfcf39941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_items', 'planned_start_date', schema='company')
    op.drop_column('planning_items', 'planned_end_date', schema='company')
    op.drop_column('planning_items', 'estimated_cost', schema='company')
    op.add_column('policies', sa.Column('entity_type', sa.String(length=100), nullable=True), schema='company')
    op.add_column('policies', sa.Column('entity_id', sa.UUID(), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'entity_id', schema='company')
    op.drop_column('policies', 'entity_type', schema='company')
    op.add_column('planning_items', sa.Column('estimated_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True), schema='company')
    op.add_column('planning_items', sa.Column('planned_end_date', sa.DATE(), autoincrement=False, nullable=True), schema='company')
    op.add_column('planning_items', sa.Column('planned_start_date', sa.DATE(), autoincrement=False, nullable=True), schema='company')
    # ### end Alembic commands ###
