"""add pinned to chat_sessions

Revision ID: 91232bae107f
Revises: 7ba8a7af3cfd
Create Date: 2026-06-21 01:10:49.002466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91232bae107f'
down_revision: Union[str, Sequence[str], None] = '7ba8a7af3cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'chat_sessions',
        sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false()),
        schema='company',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'pinned', schema='company')
    # ### end Alembic commands ###
