"""add artifact types, is_locked flags, project structure nodes, working directory path

Revision ID: 91bd82affb72
Revises: c36149f00511
Create Date: 2026-06-23 22:26:50.702369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bd82affb72'
down_revision: Union[str, Sequence[str], None] = 'c36149f00511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


NEW_ARTIFACT_TYPES = (
    "SCREEN",
    "COMPONENT",
    "REPORT",
    "DATABASE_SCHEMA",
    "TABLE",
    "STORED_PROCEDURE",
    "REFERENCE_DOC",
    "CONTEXT_BRIEF",
)


def upgrade() -> None:
    """Upgrade schema."""
    # Native Postgres enum -- SQLAlchemy stores the Python Enum member
    # NAME (uppercase) as the label, not its .value. Purely additive;
    # ADD VALUE is transactional on PG12+ so this is safe inside
    # alembic's single migration transaction.
    for label in NEW_ARTIFACT_TYPES:
        op.execute(f"ALTER TYPE public.artifact_type_enum ADD VALUE IF NOT EXISTS '{label}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_structure_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_node_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("node_type IN ('folder', 'module', 'component', 'screen', 'table', 'stored_procedure')", name='ck_project_structure_nodes_node_type'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['company.project_structure_nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['company.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='company'
    )
    op.add_column('artifacts', sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False), schema='company')
    op.add_column('planning_items', sa.Column('structure_node_id', sa.UUID(), nullable=True), schema='company')
    op.create_foreign_key(
        'fk_planning_items_structure_node_id', 'planning_items', 'project_structure_nodes',
        ['structure_node_id'], ['id'], source_schema='company', referent_schema='company',
    )
    op.add_column('projects', sa.Column('working_directory_path', sa.String(length=1024), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'working_directory_path', schema='company')
    op.drop_constraint('fk_planning_items_structure_node_id', 'planning_items', schema='company', type_='foreignkey')
    op.drop_column('planning_items', 'structure_node_id', schema='company')
    op.drop_column('artifacts', 'is_locked', schema='company')
    op.drop_table('project_structure_nodes', schema='company')
    # ### end Alembic commands ###
    # Note: Postgres cannot drop individual enum labels without
    # recreating the type, so the artifact_type_enum additions from
    # upgrade() are intentionally not reverted here.
