"""add kanboard_task_id to project_tasks

Revision ID: 9e2a27998edd
Revises: 3d0bb9a16778
Create Date: 2026-06-23 23:19:44.143666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2a27998edd'
down_revision: Union[str, Sequence[str], None] = '3d0bb9a16778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tasks', sa.Column('kanboard_task_id', sa.Integer(), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_tasks', 'kanboard_task_id', schema='company')
    # ### end Alembic commands ###
