"""add change_request_id to project_tasks and delete endpoints

Revision ID: b1ebaf76d918
Revises: 371b15d8940f
Create Date: 2026-06-25 14:43:34.735333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ebaf76d918'
down_revision: Union[str, Sequence[str], None] = '371b15d8940f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tasks', sa.Column('change_request_id', sa.UUID(), nullable=True), schema='company')
    op.create_foreign_key(None, 'project_tasks', 'change_requests', ['change_request_id'], ['id'], source_schema='company', referent_schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_tasks', schema='company', type_='foreignkey')
    op.drop_column('project_tasks', 'change_request_id', schema='company')
    # ### end Alembic commands ###
