"""add_kanboard_project_columns_to_product

Revision ID: c7ed86355d46
Revises: f5bc2f925520
Create Date: 2026-06-29 02:35:23.997537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7ed86355d46'
down_revision: Union[str, Sequence[str], None] = 'f5bc2f925520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('kanboard_project_id', sa.Integer(), nullable=True), schema='company')
    op.add_column('products', sa.Column('kanboard_column_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'kanboard_column_ids', schema='company')
    op.drop_column('products', 'kanboard_project_id', schema='company')
    # ### end Alembic commands ###
