"""add output_path to planning_items

Revision ID: df1682be2a26
Revises: b1ebaf76d918
Create Date: 2026-06-25 15:40:21.334595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1682be2a26'
down_revision: Union[str, Sequence[str], None] = 'b1ebaf76d918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_items', sa.Column('output_path', sa.String(length=1024), nullable=True), schema='company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_items', 'output_path', schema='company')
    # ### end Alembic commands ###
