"""add profiles and profile_permissions tables, add user profile_id fk

Revision ID: e19cfcf39941
Revises: c28995b0c6c4
Create Date: 2026-06-29 21:12:05.993919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19cfcf39941'
down_revision: Union[str, Sequence[str], None] = 'c28995b0c6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='company'
    )
    op.create_table('profile_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_query', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['company.profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'module', name='uq_profile_module'),
    schema='company'
    )
    op.add_column('users', sa.Column('profile_id', sa.UUID(), nullable=True), schema='company')
    op.create_foreign_key(None, 'users', 'profiles', ['profile_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='company', type_='foreignkey')
    op.drop_column('users', 'profile_id', schema='company')
    op.drop_table('profile_permissions', schema='company')
    op.drop_table('profiles', schema='company')
    # ### end Alembic commands ###
