"""add product status and cascade deletes

Revision ID: f5bc2f925520
Revises: 533f6aca2337
Create Date: 2026-06-28 23:07:16.898422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5bc2f925520'
down_revision: Union[str, Sequence[str], None] = '533f6aca2337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bug_reports_fixed_in_version_id_fkey'), 'bug_reports', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('bug_reports_planning_item_id_fkey'), 'bug_reports', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('bug_reports_detected_version_id_fkey'), 'bug_reports', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'bug_reports', 'product_versions', ['fixed_in_version_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.create_foreign_key(None, 'bug_reports', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.create_foreign_key(None, 'bug_reports', 'product_versions', ['detected_version_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.drop_constraint(op.f('change_requests_project_id_fkey'), 'change_requests', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('change_requests_plan_baseline_id_fkey'), 'change_requests', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'change_requests', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.create_foreign_key(None, 'change_requests', 'plan_baselines', ['plan_baseline_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.drop_constraint(op.f('feature_requests_planning_item_id_fkey'), 'feature_requests', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'feature_requests', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.drop_constraint(op.f('pipeline_stage_dependencies_depends_on_stage_id_fkey'), 'pipeline_stage_dependencies', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_stage_dependencies', 'pipeline_stages', ['depends_on_stage_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('pipeline_stages_pipeline_id_fkey'), 'pipeline_stages', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_stages', 'project_pipelines', ['pipeline_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('plan_baselines_project_plan_id_fkey'), 'plan_baselines', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'plan_baselines', 'project_plans', ['project_plan_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_planning_items_structure_node_id'), 'planning_items', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('planning_items_target_version_id_fkey'), 'planning_items', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('planning_items_project_id_fkey'), 'planning_items', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'planning_items', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.create_foreign_key(None, 'planning_items', 'project_structure_nodes', ['structure_node_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.create_foreign_key(None, 'planning_items', 'product_versions', ['target_version_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.add_column('products', sa.Column('status', sa.String(length=30), server_default='active', nullable=False), schema='company')
    op.drop_constraint(op.f('project_forgerouter_configs_project_id_fkey'), 'project_forgerouter_configs', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'project_forgerouter_configs', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('project_pipelines_project_id_fkey'), 'project_pipelines', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'project_pipelines', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('project_plans_project_id_fkey'), 'project_plans', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'project_plans', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('project_structure_nodes_project_id_fkey'), 'project_structure_nodes', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('project_structure_nodes_parent_node_id_fkey'), 'project_structure_nodes', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'project_structure_nodes', 'project_structure_nodes', ['parent_node_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.create_foreign_key(None, 'project_structure_nodes', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('project_tasks_parent_task_id_fkey'), 'project_tasks', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('project_tasks_change_request_id_fkey'), 'project_tasks', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('project_tasks_planning_item_id_fkey'), 'project_tasks', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'project_tasks', 'project_tasks', ['parent_task_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.create_foreign_key(None, 'project_tasks', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.create_foreign_key(None, 'project_tasks', 'change_requests', ['change_request_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.drop_constraint(op.f('projects_product_version_id_fkey'), 'projects', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'product_versions', ['product_version_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('task_assignments_task_id_fkey'), 'task_assignments', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'task_assignments', 'project_tasks', ['task_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('task_dependencies_task_id_fkey'), 'task_dependencies', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('task_dependencies_depends_on_task_id_fkey'), 'task_dependencies', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'task_dependencies', 'project_tasks', ['task_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.create_foreign_key(None, 'task_dependencies', 'project_tasks', ['depends_on_task_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('task_executions_assignment_id_fkey'), 'task_executions', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('task_executions_task_id_fkey'), 'task_executions', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'task_executions', 'project_tasks', ['task_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.create_foreign_key(None, 'task_executions', 'task_assignments', ['assignment_id'], ['id'], source_schema='company', referent_schema='company', ondelete='SET NULL')
    op.drop_constraint(op.f('task_required_skills_task_id_fkey'), 'task_required_skills', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'task_required_skills', 'project_tasks', ['task_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('triage_decisions_planning_item_id_fkey'), 'triage_decisions', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'triage_decisions', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.drop_constraint(op.f('version_scope_items_product_version_id_fkey'), 'version_scope_items', schema='company', type_='foreignkey')
    op.drop_constraint(op.f('version_scope_items_planning_item_id_fkey'), 'version_scope_items', schema='company', type_='foreignkey')
    op.create_foreign_key(None, 'version_scope_items', 'product_versions', ['product_version_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    op.create_foreign_key(None, 'version_scope_items', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version_scope_items', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'version_scope_items', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('version_scope_items_planning_item_id_fkey'), 'version_scope_items', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('version_scope_items_product_version_id_fkey'), 'version_scope_items', 'product_versions', ['product_version_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'triage_decisions', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('triage_decisions_planning_item_id_fkey'), 'triage_decisions', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'task_required_skills', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('task_required_skills_task_id_fkey'), 'task_required_skills', 'project_tasks', ['task_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'task_executions', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'task_executions', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('task_executions_task_id_fkey'), 'task_executions', 'project_tasks', ['task_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('task_executions_assignment_id_fkey'), 'task_executions', 'task_assignments', ['assignment_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'task_dependencies', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'task_dependencies', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('task_dependencies_depends_on_task_id_fkey'), 'task_dependencies', 'project_tasks', ['depends_on_task_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('task_dependencies_task_id_fkey'), 'task_dependencies', 'project_tasks', ['task_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'task_assignments', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('task_assignments_task_id_fkey'), 'task_assignments', 'project_tasks', ['task_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'projects', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('projects_product_version_id_fkey'), 'projects', 'product_versions', ['product_version_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'project_tasks', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'project_tasks', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'project_tasks', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('project_tasks_planning_item_id_fkey'), 'project_tasks', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('project_tasks_change_request_id_fkey'), 'project_tasks', 'change_requests', ['change_request_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('project_tasks_parent_task_id_fkey'), 'project_tasks', 'project_tasks', ['parent_task_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'project_structure_nodes', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'project_structure_nodes', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('project_structure_nodes_parent_node_id_fkey'), 'project_structure_nodes', 'project_structure_nodes', ['parent_node_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('project_structure_nodes_project_id_fkey'), 'project_structure_nodes', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'project_plans', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('project_plans_project_id_fkey'), 'project_plans', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'project_pipelines', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('project_pipelines_project_id_fkey'), 'project_pipelines', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'project_forgerouter_configs', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('project_forgerouter_configs_project_id_fkey'), 'project_forgerouter_configs', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_column('products', 'status', schema='company')
    op.drop_constraint(None, 'planning_items', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'planning_items', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'planning_items', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('planning_items_project_id_fkey'), 'planning_items', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('planning_items_target_version_id_fkey'), 'planning_items', 'product_versions', ['target_version_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('fk_planning_items_structure_node_id'), 'planning_items', 'project_structure_nodes', ['structure_node_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'plan_baselines', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('plan_baselines_project_plan_id_fkey'), 'plan_baselines', 'project_plans', ['project_plan_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'pipeline_stages', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_stages_pipeline_id_fkey'), 'pipeline_stages', 'project_pipelines', ['pipeline_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'pipeline_stage_dependencies', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_stage_dependencies_depends_on_stage_id_fkey'), 'pipeline_stage_dependencies', 'pipeline_stages', ['depends_on_stage_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'feature_requests', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('feature_requests_planning_item_id_fkey'), 'feature_requests', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'change_requests', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'change_requests', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('change_requests_plan_baseline_id_fkey'), 'change_requests', 'plan_baselines', ['plan_baseline_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('change_requests_project_id_fkey'), 'change_requests', 'projects', ['project_id'], ['id'], source_schema='company', referent_schema='company')
    op.drop_constraint(None, 'bug_reports', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'bug_reports', schema='company', type_='foreignkey')
    op.drop_constraint(None, 'bug_reports', schema='company', type_='foreignkey')
    op.create_foreign_key(op.f('bug_reports_detected_version_id_fkey'), 'bug_reports', 'product_versions', ['detected_version_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('bug_reports_planning_item_id_fkey'), 'bug_reports', 'planning_items', ['planning_item_id'], ['id'], source_schema='company', referent_schema='company')
    op.create_foreign_key(op.f('bug_reports_fixed_in_version_id_fkey'), 'bug_reports', 'product_versions', ['fixed_in_version_id'], ['id'], source_schema='company', referent_schema='company')
    # ### end Alembic commands ###
